name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Enable debug logs globally for all steps
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}  # Added at the job level

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mattjblanch/hello-docker:latest

      - name: Debug Docker Image
        run: |
          docker pull mattjblanch/hello-docker:latest
          docker inspect mattjblanch/hello-docker:latest

      - name: Verify app_spec.yaml
        run: cat app_spec.yaml

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Debug doctl Installation
        run: |
          doctl version
          doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Debug Secrets
        run: echo "DIGITALOCEAN_APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}"

      - name: Deploy to DigitalOcean App Platform
        run: |
          doctl version
          doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }} --spec app_spec.yaml