name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
    build:
      runs-on: node:14-alpine
      steps:
        - name: Checkout Code
        uses: actions/checkout@v3

        - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

        - name: Install Dependencies
        run: npm install

        - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mattjblanch/hello-docker:latest

        - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

        - name: Deploy to DigitalOcean App Platform
        run: doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }}





















